import {loadState,saveState,resetState,uid} from './storage.js';

const app=document.querySelector('#app');
let state=loadState();
let route='dashboard';
let packs=[];
let modal=null;

const nav=[
  ['dashboard','Dashboard'],['contacts','Contacts'],['quotes','Quotes'],['tenders','Tenders'],['projects','Projects'],['schedule','Schedule'],['field','Field'],['health','Health & Safety'],['rates','Rates'],['timesheets','Timesheets'],['claims','Claims'],['invoices','Invoices'],['reports','Reports'],['settings','Settings']
];
const money=n=>new Intl.NumberFormat('en-NZ',{style:'currency',currency:state.settings?.currency||'NZD',maximumFractionDigits:0}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const getProject=id=>state.projects.find(p=>p.id===id);
const getCrew=id=>state.crew.find(c=>c.id===id);
const getContact=id=>state.contacts.find(c=>c.id===id);
const enabledPacks=()=>packs.filter(p=>state.workspace.trades.includes(p.id));
const quoteTotal=q=>(q.lines||[]).reduce((s,l)=>s+Number(l.qty||0)*Number(l.rate||0),0);
const approvedVariations=projectId=>state.variations.filter(v=>v.projectId===projectId&&v.status==='Approved').reduce((s,v)=>s+Number(v.value||0),0);
const adjustedContract=p=>Number(p.contract||0)+approvedVariations(p.id);
const projectValueToDate=p=>adjustedContract(p)*Number(p.progress||0)/100;
const claimedToDate=projectId=>state.claims.filter(c=>c.projectId===projectId).reduce((s,c)=>s+Number(c.value||0),0);

async function loadPacks(){
  const files=['earthworks-landscaping-drainage','painting-decorating','building-carpentry'];
  packs=await Promise.all(files.map(id=>fetch(`trade-packs/${id}.json`).then(r=>r.json())));
}

function notify(message){
  const n=document.createElement('div');n.className='toast';n.textContent=message;document.body.appendChild(n);setTimeout(()=>n.classList.add('show'),20);setTimeout(()=>n.remove(),2600);
}
function persist(msg){saveState(state);render();if(msg)notify(msg)}
function openModal(title,body,actions=''){
  modal={title,body,actions};renderModal();
}
function closeModal(){modal=null;document.querySelector('#modalRoot')?.remove()}
function renderModal(){
  document.querySelector('#modalRoot')?.remove();if(!modal)return;
  const root=document.createElement('div');root.id='modalRoot';root.className='modal-backdrop';root.innerHTML=`<div class="modal"><div class="modal-head"><h2>${esc(modal.title)}</h2><button class="icon-btn" id="closeModal">×</button></div><div class="modal-body">${modal.body}</div><div class="modal-actions">${modal.actions||'<button class="btn secondary" id="closeModal2">Close</button>'}</div></div>`;
  document.body.appendChild(root);root.querySelector('#closeModal')?.addEventListener('click',closeModal);root.querySelector('#closeModal2')?.addEventListener('click',closeModal);
}
function shell(content){
  const unread=(state.notifications||[]).filter(n=>!n.read).length;
  app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">TradeOS</div><div class="workspace"><strong>${esc(state.workspace.name)}</strong><br><span class="muted">NZ contractor operations</span></div><nav class="nav">${nav.map(([id,label])=>`<button data-route="${id}" class="${route===id?'active':''}">${label}</button>`).join('')}</nav></aside><main class="main"><div class="topbar"><div><div class="kicker">${esc(state.workspace.name)}</div><h1>${nav.find(n=>n[0]===route)?.[1]||'TradeOS'}</h1></div><div class="row"><span class="pill">${state.workspace.trades.length} trade pack${state.workspace.trades.length===1?'':'s'}</span>${unread?`<span class="pill alert">${unread} alert${unread===1?'':'s'}</span>`:''}</div></div>${content}</main></div><div class="mobilebar">${nav.map(([id,label])=>`<button data-route="${id}" class="${route===id?'active':''}">${label}</button>`).join('')}</div>`;
  document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route=b.dataset.route;render()});
}
const stat=(label,value,sub='')=>`<div class="card stat"><div class="label">${label}</div><div class="metric">${value}</div>${sub?`<div class="muted small">${sub}</div>`:''}</div>`;
const badge=s=>`<span class="badge ${String(s).toLowerCase().replace(/\s+/g,'-')}">${esc(s)}</span>`;

function dashboard(){
  const active=state.projects.filter(p=>p.status==='In progress');
  const unapproved=state.variations.filter(v=>v.status!=='Approved').reduce((s,v)=>s+Number(v.value||0),0);
  const outstanding=state.invoices.filter(i=>i.status!=='Paid').reduce((s,i)=>s+Number(i.total||0),0);
  const todays=(state.schedule||[]).filter(s=>s.date===today());
  return `<section class="hero"><div class="kicker light">TRADEOS</div><h2>Run the office and the site from one place.</h2><p>Quote it, schedule it, manage the crew, capture field evidence, control variations, claim progress and invoice — with the rate and H&S libraries matched to the work you actually do.</p></section>
  <div class="grid">${stat('Active jobs',active.length)}${stat('Unapproved variations',money(unapproved))}${stat('Outstanding invoices',money(outstanding))}${stat('Crew',state.crew.filter(c=>c.active).length)}</div>
  <div class="dashboard-grid section"><div class="card"><div class="section-head"><h2>Today</h2><button class="link-btn" data-route="schedule">Open schedule</button></div>${todays.length?todays.map(s=>{const p=getProject(s.projectId);return `<div class="list-row"><div><strong>${esc(p?.name||s.projectId)}</strong><div class="muted small">${s.start}–${s.end} · ${(s.crewIds||[]).map(id=>getCrew(id)?.name).filter(Boolean).join(', ')}</div></div><span>${badge('Scheduled')}</span></div>`}).join(''):'<div class="empty">Nothing scheduled today.</div>'}</div>
  <div class="card"><div class="section-head"><h2>Needs attention</h2></div>${state.variations.filter(v=>v.status!=='Approved').map(v=>`<div class="list-row"><div><strong>${esc(v.id)} · ${esc(getProject(v.projectId)?.name||v.projectId)}</strong><div class="muted small">${esc(v.description)}</div></div><strong>${money(v.value)}</strong></div>`).join('')||'<div class="empty">No urgent exceptions.</div>'}</div></div>
  <section class="section"><div class="card"><div class="section-head"><h2>Active jobs</h2><button class="btn secondary" data-route="projects">View all</button></div>${active.map(p=>`<div class="project-strip"><div><strong>${esc(p.name)}</strong><div class="muted small">${esc(p.site||'')} · ${esc(p.trade)}</div></div><div class="progress"><span style="width:${Math.max(0,Math.min(100,p.progress))}%"></span></div><strong>${p.progress}%</strong></div>`).join('')}</div></section>`;
}

function contacts(){return `<div class="row"><button class="btn" id="newContact">New contact</button></div><section class="section"><div class="card table-wrap"><table class="table"><thead><tr><th>Name</th><th>Company</th><th>Type</th><th></th></tr></thead><tbody>${state.contacts.map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.company||'')}</td><td>${badge(c.type||'Contact')}</td><td><button class="link-btn edit-contact" data-id="${c.id}">Edit</button></td></tr>`).join('')}</tbody></table></div></section>`}

function quotes(){return `<div class="row"><button class="btn" id="newQuote">New quote</button></div><section class="section"><div class="card table-wrap"><table class="table"><thead><tr><th>Quote</th><th>Client</th><th>Scope</th><th>Value excl. GST</th><th>Status</th><th></th></tr></thead><tbody>${state.quotes.map(q=>`<tr><td>${esc(q.id)}</td><td>${esc(getContact(q.clientId)?.name||'')}</td><td><strong>${esc(q.title)}</strong></td><td>${money(quoteTotal(q))}</td><td>${badge(q.status)}</td><td><button class="link-btn view-quote" data-id="${q.id}">Open</button></td></tr>`).join('')}</tbody></table></div></section>`}

function tenders(){return `<div class="row"><button class="btn" id="newTender">New tender</button></div><section class="section"><div class="card table-wrap"><table class="table"><thead><tr><th>Tender</th><th>Client</th><th>Opportunity</th><th>Closing</th><th>Status</th><th></th></tr></thead><tbody>${(state.tenders||[]).map(t=>`<tr><td>${esc(t.id)}</td><td>${esc(getContact(t.clientId)?.company||getContact(t.clientId)?.name||'')}</td><td><strong>${esc(t.title)}</strong></td><td>${esc(t.closingDate)}</td><td>${badge(t.status)}</td><td><button class="link-btn view-tender" data-id="${t.id}">Open</button></td></tr>`).join('')}</tbody></table></div></section>`}

function projects(){return `<div class="row"><button class="btn" id="newProject">New project</button></div><section class="section"><div class="cards-list">${state.projects.map(p=>`<button class="card project-card open-project" data-id="${p.id}"><div class="project-main"><div class="kicker">${esc(p.id)} · ${esc(p.trade)}</div><h3>${esc(p.name)}</h3><div class="muted">${esc(p.site||'')}</div></div><div class="project-money"><strong>${money(adjustedContract(p))}</strong><span>${badge(p.status)}</span></div><div class="progress wide"><span style="width:${p.progress}%"></span></div><div class="muted small">${p.progress}% complete · ${(p.crew||[]).map(id=>getCrew(id)?.name).filter(Boolean).join(', ')}</div></button>`).join('')}</div></section>`}

function schedule(){
  const rows=[...(state.schedule||[])].sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`));
  return `<div class="row"><button class="btn" id="newSchedule">Schedule crew</button><span class="muted small">TradeOS is the source of truth. Calendar integrations can sync outward.</span></div><section class="section"><div class="card table-wrap"><table class="table"><thead><tr><th>Date</th><th>Time</th><th>Job</th><th>Crew</th><th>Plan</th><th></th></tr></thead><tbody>${rows.map(s=>`<tr><td><strong>${esc(s.date)}</strong></td><td>${esc(s.start)}–${esc(s.end)}</td><td>${esc(getProject(s.projectId)?.name||s.projectId)}</td><td>${(s.crewIds||[]).map(id=>esc(getCrew(id)?.name||id)).join(', ')}</td><td>${esc(s.note||'')}</td><td><button class="link-btn delete-schedule" data-id="${s.id}">Remove</button></td></tr>`).join('')}</tbody></table></div></section>`;
}

function field(){
  const fs=state.fieldSession||{crewId:null,projectId:null,clockedIn:false,hnsSigned:false};
  const crew=getCrew(fs.crewId);const p=getProject(fs.projectId);
  if(!crew){return `<div class="field-shell"><div class="field-phone card"><div class="kicker">FIELD APP</div><h2>Sign in</h2><p class="muted">Select your profile to start the day.</p><div class="stack">${state.crew.filter(c=>c.active&&c.role==='worker_crew').map(c=>`<button class="action-card sign-crew" data-id="${c.id}"><span class="avatar">${esc(c.name.slice(0,1))}</span><span><strong>${esc(c.name)}</strong><small>Field crew</small></span><b>›</b></button>`).join('')}</div></div><div class="card field-help"><h3>Field workflow</h3><ol><li>Sign in</li><li>Open assigned job</li><li>Clock in</li><li>Complete H&S sign-on</li><li>Capture progress, photos, materials, hazards and variations</li><li>Clock out</li></ol></div></div>`}
  if(!p){const jobs=state.projects.filter(x=>x.status==='In progress'&&(x.crew||[]).includes(crew.id));return `<div class="field-shell"><div class="field-phone card"><div class="field-user"><div><div class="kicker">SIGNED IN</div><h2>${esc(crew.name)}</h2></div><button class="btn secondary" id="fieldSignOut">Sign out</button></div><h3>Today’s jobs</h3><div class="stack">${jobs.map(j=>`<button class="action-card field-job" data-id="${j.id}"><span><strong>${esc(j.name)}</strong><small>${esc(j.site||'')} · ${j.progress}% complete</small></span><b>›</b></button>`).join('')||'<div class="empty">No assigned jobs.</div>'}</div></div><div class="card field-help"><h3>Assigned crew</h3><p>${esc(crew.name)}</p><p class="muted small">Jobs are filtered to the crew assignment set in the project and schedule.</p></div></div>`}
  const lastProgress=(state.progressUpdates||[]).filter(x=>x.projectId===p.id).slice(-1)[0];
  return `<div class="field-shell"><div class="field-phone card"><div class="field-user"><div><div class="kicker">${esc(crew.name)}</div><h2>${esc(p.name)}</h2><div class="muted small">${esc(p.site||'')}</div></div><button class="btn secondary" id="backToJobs">Jobs</button></div>
  <div class="field-status"><span>${fs.clockedIn?badge('Clocked in'):badge('Not clocked in')}</span><span>${fs.hnsSigned?badge('H&S signed'):badge('H&S required')}</span></div>
  ${!fs.clockedIn?`<button class="btn field-primary" id="clockIn">Clock in</button>`:`${!fs.hnsSigned?`<button class="btn field-primary" id="hnsSign">Complete H&S sign-on</button>`:`<div class="field-actions"><button class="action-card" id="fieldProgress"><span><strong>Update progress</strong><small>Current project progress: ${p.progress}%</small></span><b>›</b></button><button class="action-card" id="fieldPhoto"><span><strong>Add photo evidence</strong><small>${lastProgress?.photos||0} photo${Number(lastProgress?.photos||0)===1?'':'s'} on latest update</small></span><b>›</b></button><button class="action-card" id="fieldVariation"><span><strong>Flag a variation</strong><small>Capture scope and estimated value</small></span><b>›</b></button><button class="action-card" id="fieldMaterial"><span><strong>Request materials</strong><small>Send request to office</small></span><b>›</b></button><button class="action-card" id="fieldHazard"><span><strong>Report hazard / safety issue</strong><small>Create immediate H&S record</small></span><b>›</b></button><button class="action-card danger" id="clockOut"><span><strong>Clock out</strong><small>Close current timesheet</small></span><b>›</b></button></div>`}`}
  </div><div class="card field-help"><div class="kicker">JOB STATUS</div><h3>${p.progress}% complete</h3><div class="progress wide"><span style="width:${p.progress}%"></span></div><div class="section">${(p.stages||[]).map(s=>`<div class="stage-row"><span>${esc(s.name)}</span><strong>${s.pct}%</strong></div>`).join('')}</div></div></div>`;
}

function health(){
  const hazards=[...new Set(enabledPacks().flatMap(p=>p.hazards||[]))];
  return `<div class="row"><button class="btn" id="newHns">New H&S document</button><button class="btn secondary" id="newHazard">Report hazard</button></div><div class="dashboard-grid section"><div class="card"><div class="section-head"><h2>Project H&S</h2></div>${(state.hnsDocs||[]).map(d=>`<div class="list-row"><div><strong>${esc(d.type)} · ${esc(getProject(d.projectId)?.name||'')}</strong><div class="muted small">${esc(d.date)} · ${(d.hazards||[]).join(', ')}</div></div>${badge(d.status)}</div>`).join('')||'<div class="empty">No H&S documents.</div>'}</div><div class="card"><h2>Enabled hazard library</h2>${hazards.map(h=>`<div class="hazard-line">${esc(h)}</div>`).join('')}<div class="notice section"><strong>Company responsibility:</strong> starter templates must be reviewed and adopted for the actual work and site.</div></div></div>
  <section class="section"><div class="card"><h2>Hazard / incident reports</h2>${(state.hazardReports||[]).map(h=>`<div class="list-row"><div><strong>${esc(h.type||'Hazard')} · ${esc(getProject(h.projectId)?.name||'')}</strong><div class="muted small">${esc(h.date)} · ${esc(h.description)}</div></div>${badge(h.status||'Open')}</div>`).join('')||'<div class="empty">No open reports.</div>'}</div></section>`;
}

function rates(){
  const enabled=enabledPacks();return `<div class="notice">Starter rates are editable defaults only. Each company should confirm its labour, plant, material, subcontract and margin assumptions before quoting.</div><section class="section"><div class="cards-list">${enabled.map(p=>`<div class="card"><div class="kicker">TRADE PACK</div><h2>${esc(p.name)}</h2><div class="chip-row">${(p.rateCategories||[]).map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div><div class="section"><h3>Typical job types</h3><div class="muted">${(p.jobTypes||[]).join(' · ')}</div></div><div class="section"><button class="btn secondary edit-rates" data-id="${p.id}">Edit company rates</button></div></div>`).join('')}</div></section>`;
}

function timesheets(){return `<div class="row"><button class="btn" id="newTimesheet">Add timesheet</button></div><section class="section"><div class="card table-wrap"><table class="table"><thead><tr><th>Date</th><th>Crew</th><th>Job</th><th>Start</th><th>Finish</th><th>Hours</th><th>Status</th></tr></thead><tbody>${(state.timesheets||[]).map(t=>`<tr><td>${esc(t.date)}</td><td>${esc(getCrew(t.crewId)?.name||'')}</td><td>${esc(getProject(t.projectId)?.name||'')}</td><td>${esc(t.start)}</td><td>${esc(t.end||'—')}</td><td>${Number(t.hours||0).toFixed(2)}</td><td>${badge(t.status||'Draft')}</td></tr>`).join('')}</tbody></table></div></section>`}

function claims(){return `<div class="row"><button class="btn" id="newClaim">New progress claim</button></div><div class="notice section"><strong>Progress Claim ≠ Tax Invoice.</strong> The claim values completed work against the contract; the invoice is the payment document.</div><section class="section"><div class="card table-wrap"><table class="table"><thead><tr><th>Claim</th><th>Project</th><th>Adjusted contract</th><th>Value this claim</th><th>Linked invoice</th><th>Status</th><th></th></tr></thead><tbody>${state.claims.map(c=>`<tr><td>${esc(c.id)}</td><td>${esc(getProject(c.projectId)?.name||'')}</td><td>${money(c.adjustedContract)}</td><td><strong>${money(c.value)}</strong></td><td>${esc(c.invoiceId||'—')}</td><td>${badge(c.status)}</td><td><button class="link-btn claim-invoice" data-id="${c.id}">${c.invoiceId?'Open invoice':'Create invoice'}</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No claims yet.</td></tr>'}</tbody></table></div></section>`}

function invoices(){return `<div class="row"><button class="btn" id="newInvoice">New invoice</button></div><section class="section"><div class="card table-wrap"><table class="table"><thead><tr><th>Invoice</th><th>Project</th><th>Linked claim</th><th>Subtotal</th><th>GST</th><th>Total</th><th>Status</th></tr></thead><tbody>${state.invoices.map(i=>`<tr><td>${esc(i.id)}</td><td>${esc(getProject(i.projectId)?.name||'')}</td><td>${esc(i.claimId||'—')}</td><td>${money(i.subtotal)}</td><td>${money(i.gst)}</td><td><strong>${money(i.total)}</strong></td><td>${badge(i.status)}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No invoices yet.</td></tr>'}</tbody></table></div></section>`}

function reports(){
  const contract=state.projects.reduce((s,p)=>s+adjustedContract(p),0);const captured=state.variations.reduce((s,v)=>s+Number(v.value||0),0);const hours=state.timesheets.reduce((s,t)=>s+Number(t.hours||0),0);const quoted=state.quotes.reduce((s,q)=>s+quoteTotal(q),0);
  return `<div class="grid">${stat('Live contract value',money(contract))}${stat('Quoted pipeline',money(quoted))}${stat('Variations captured',money(captured))}${stat('Recorded labour',hours.toFixed(1)+' h')}</div><div class="dashboard-grid section"><div class="card"><h2>Project progress</h2>${state.projects.map(p=>`<div class="project-strip"><div><strong>${esc(p.name)}</strong><div class="muted small">${money(adjustedContract(p))}</div></div><div class="progress"><span style="width:${p.progress}%"></span></div><strong>${p.progress}%</strong></div>`).join('')}</div><div class="card"><h2>Commercial position</h2>${state.projects.map(p=>`<div class="stage-row"><span>${esc(p.name)} value to date</span><strong>${money(projectValueToDate(p))}</strong></div><div class="stage-row"><span>Claimed to date</span><strong>${money(claimedToDate(p.id))}</strong></div>`).join('')}</div></div>`;
}

function settings(){return `<div class="dashboard-grid"><div class="card"><h2>Company</h2><div class="form-grid"><div class="field"><label>Company name</label><input id="companyName" value="${esc(state.workspace.name)}"></div><div class="field"><label>Legal name</label><input id="legalName" value="${esc(state.workspace.legalName||'')}"></div><div class="field"><label>GST number</label><input id="gst" value="${esc(state.workspace.gst||'')}"></div><div class="field"><label>Email</label><input id="email" value="${esc(state.workspace.email||'')}"></div><div class="field"><label>Phone</label><input id="phone" value="${esc(state.workspace.phone||'')}"></div><div class="field"><label>Bank account</label><input id="bank" value="${esc(state.workspace.bank||'')}"></div><div class="field full"><label>Business address</label><input id="address" value="${esc(state.workspace.address||'')}"></div><div class="field full"><label>H&S policy</label><input value="${esc(state.workspace.hnsPolicyName||'Not uploaded')}" readonly></div></div><div class="row section"><button class="btn" id="saveCompany">Save company details</button><button class="btn secondary" id="resetDemo">Reset demo data</button></div></div><div class="card"><h2>Trade packs</h2><p class="muted small">Only enabled packs feed job types, progress stages, H&S hazards, materials and rate categories into the workspace.</p>${packs.map(p=>`<label class="trade-card card"><div class="row"><input type="checkbox" data-pack="${p.id}" ${state.workspace.trades.includes(p.id)?'checked':''}><strong>${esc(p.name)}</strong></div><div class="muted small">${esc(p.description)}</div><div class="chip-row">${p.jobTypes.slice(0,4).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div></label>`).join('')}</div></div>`}

function bind(){
  document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route=b.dataset.route;render()});
  document.querySelector('#newContact')?.addEventListener('click',()=>{openModal('New contact',`<div class="form-grid"><div class="field"><label>Name</label><input id="mName"></div><div class="field"><label>Company</label><input id="mCompany"></div><div class="field"><label>Type</label><select id="mType"><option>Client</option><option>Main contractor</option><option>Supplier</option><option>Subcontractor</option></select></div></div>`,`<button class="btn" id="saveNewContact">Save contact</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveNewContact').onclick=()=>{const name=document.querySelector('#mName').value.trim();if(!name)return;state.contacts.push({id:uid('C'),name,company:document.querySelector('#mCompany').value.trim(),type:document.querySelector('#mType').value});saveState(state);closeModal();render();notify('Contact saved')}});
  document.querySelector('#newQuote')?.addEventListener('click',()=>quoteEditor());
  document.querySelectorAll('.view-quote').forEach(b=>b.onclick=()=>quoteEditor(b.dataset.id));
  document.querySelector('#newTender')?.addEventListener('click',()=>tenderEditor());
  document.querySelectorAll('.view-tender').forEach(b=>b.onclick=()=>tenderEditor(b.dataset.id));
  document.querySelector('#newProject')?.addEventListener('click',()=>projectEditor());
  document.querySelectorAll('.open-project').forEach(b=>b.onclick=()=>projectEditor(b.dataset.id));
  document.querySelector('#newSchedule')?.addEventListener('click',scheduleEditor);
  document.querySelectorAll('.delete-schedule').forEach(b=>b.onclick=()=>{state.schedule=state.schedule.filter(x=>x.id!==b.dataset.id);persist('Schedule item removed')});
  document.querySelectorAll('.sign-crew').forEach(b=>b.onclick=()=>{state.fieldSession={crewId:b.dataset.id,projectId:null,clockedIn:false,clockInAt:null,hnsSigned:false};persist('Signed in')});
  document.querySelector('#fieldSignOut')?.addEventListener('click',()=>{state.fieldSession={crewId:null,projectId:null,clockedIn:false,clockInAt:null,hnsSigned:false};persist('Signed out')});
  document.querySelectorAll('.field-job').forEach(b=>b.onclick=()=>{state.fieldSession.projectId=b.dataset.id;persist()});
  document.querySelector('#backToJobs')?.addEventListener('click',()=>{state.fieldSession.projectId=null;persist()});
  document.querySelector('#clockIn')?.addEventListener('click',clockIn);
  document.querySelector('#hnsSign')?.addEventListener('click',fieldHns);
  document.querySelector('#fieldProgress')?.addEventListener('click',fieldProgress);
  document.querySelector('#fieldPhoto')?.addEventListener('click',fieldPhoto);
  document.querySelector('#fieldVariation')?.addEventListener('click',fieldVariation);
  document.querySelector('#fieldMaterial')?.addEventListener('click',fieldMaterial);
  document.querySelector('#fieldHazard')?.addEventListener('click',fieldHazard);
  document.querySelector('#clockOut')?.addEventListener('click',clockOut);
  document.querySelector('#newHns')?.addEventListener('click',newHnsDoc);
  document.querySelector('#newHazard')?.addEventListener('click',()=>fieldHazard(true));
  document.querySelector('#newTimesheet')?.addEventListener('click',manualTimesheet);
  document.querySelector('#newClaim')?.addEventListener('click',newClaim);
  document.querySelector('#newInvoice')?.addEventListener('click',()=>newInvoice());
  document.querySelectorAll('.claim-invoice').forEach(b=>b.onclick=()=>{const c=state.claims.find(x=>x.id===b.dataset.id);if(c.invoiceId){route='invoices';render()}else newInvoice(c.id)});
  document.querySelector('#saveCompany')?.addEventListener('click',()=>{for(const [id,key] of [['companyName','name'],['legalName','legalName'],['gst','gst'],['email','email'],['phone','phone'],['bank','bank'],['address','address']])state.workspace[key]=document.querySelector('#'+id).value.trim();persist('Company details saved')});
  document.querySelector('#resetDemo')?.addEventListener('click',()=>{if(confirm('Reset all TradeOS demo data?')){state=resetState();render();notify('Demo reset')}});
  document.querySelectorAll('[data-pack]').forEach(cb=>cb.onchange=()=>{const id=cb.dataset.pack;state.workspace.trades=cb.checked?[...new Set([...state.workspace.trades,id])]:state.workspace.trades.filter(x=>x!==id);persist('Trade packs updated')});
  document.querySelectorAll('.edit-rates').forEach(b=>b.onclick=()=>openModal('Company rate library',`<p>Rate editing is company-specific. The enabled <strong>${esc(packs.find(p=>p.id===b.dataset.id)?.name||'trade')}</strong> categories are available to quote builders.</p><div class="notice">Starter pricing is deliberately editable and should be confirmed during onboarding.</div>`));
}

function quoteEditor(id){
  const existing=state.quotes.find(q=>q.id===id);const q=existing||{id:uid('Q'),clientId:state.contacts[0]?.id||'',title:'',trade:state.workspace.trades[0]||'',status:'Draft',date:today(),validUntil:today(),notes:'',lines:[]};
  openModal(existing?`Quote ${q.id}`:'New quote',`<div class="form-grid"><div class="field"><label>Client</label><select id="qClient">${state.contacts.filter(c=>c.type==='Client'||c.type==='Main contractor').map(c=>`<option value="${c.id}" ${c.id===q.clientId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Status</label><select id="qStatus">${['Draft','Sent','Accepted','Declined'].map(x=>`<option ${x===q.status?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><label>Scope / title</label><input id="qTitle" value="${esc(q.title)}"></div></div><div class="section"><h3>Line items</h3><div id="quoteLines">${(q.lines||[]).map((l,i)=>lineRow(l,i)).join('')}</div><button class="btn secondary" id="addQuoteLine">Add line</button></div><div class="field section"><label>Notes</label><textarea id="qNotes">${esc(q.notes||'')}</textarea></div>`,`<button class="btn" id="saveQuote">Save quote</button><button class="btn secondary" id="closeModal2">Cancel</button>`);
  document.querySelector('#addQuoteLine').onclick=()=>{document.querySelector('#quoteLines').insertAdjacentHTML('beforeend',lineRow({description:'',qty:1,unit:'item',rate:0},document.querySelectorAll('.quote-line').length))};
  document.querySelector('#saveQuote').onclick=()=>{q.clientId=document.querySelector('#qClient').value;q.status=document.querySelector('#qStatus').value;q.title=document.querySelector('#qTitle').value.trim();q.notes=document.querySelector('#qNotes').value.trim();q.lines=[...document.querySelectorAll('.quote-line')].map(r=>({id:r.dataset.id||uid('QL'),description:r.querySelector('.ql-desc').value,qty:Number(r.querySelector('.ql-qty').value||0),unit:r.querySelector('.ql-unit').value,rate:Number(r.querySelector('.ql-rate').value||0)}));if(!existing)state.quotes.unshift(q);saveState(state);closeModal();render();notify('Quote saved')};
}
function lineRow(l,i){return `<div class="quote-line" data-id="${esc(l.id||'')}"><input class="ql-desc" placeholder="Description" value="${esc(l.description||'')}"><input class="ql-qty" type="number" step="0.01" value="${Number(l.qty||1)}"><input class="ql-unit" value="${esc(l.unit||'item')}"><input class="ql-rate" type="number" step="0.01" value="${Number(l.rate||0)}"></div>`}
function tenderEditor(id){
  const existing=(state.tenders||[]).find(t=>t.id===id);const t=existing||{id:uid('T'),clientId:state.contacts[0]?.id||'',title:'',trade:state.workspace.trades[0]||'',status:'Draft',closingDate:today(),scope:'',methodology:''};
  openModal(existing?`Tender ${t.id}`:'New tender',`<div class="form-grid"><div class="field"><label>Client</label><select id="tClient">${state.contacts.map(c=>`<option value="${c.id}" ${c.id===t.clientId?'selected':''}>${esc(c.company||c.name)}</option>`).join('')}</select></div><div class="field"><label>Closing date</label><input type="date" id="tClose" value="${esc(t.closingDate)}"></div><div class="field full"><label>Opportunity</label><input id="tTitle" value="${esc(t.title)}"></div><div class="field full"><label>Scope</label><textarea id="tScope">${esc(t.scope)}</textarea></div><div class="field full"><label>Methodology</label><textarea id="tMethod">${esc(t.methodology)}</textarea></div></div>`,`<button class="btn" id="saveTender">Save tender</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveTender').onclick=()=>{t.clientId=document.querySelector('#tClient').value;t.closingDate=document.querySelector('#tClose').value;t.title=document.querySelector('#tTitle').value.trim();t.scope=document.querySelector('#tScope').value.trim();t.methodology=document.querySelector('#tMethod').value.trim();if(!existing){state.tenders=state.tenders||[];state.tenders.unshift(t)}saveState(state);closeModal();render();notify('Tender saved')};
}
function projectEditor(id){
  const existing=state.projects.find(p=>p.id===id);const p=existing||{id:uid('PJ'),clientId:state.contacts[0]?.id||'',name:'',site:'',trade:state.workspace.trades[0]||'',status:'In progress',contract:0,progress:0,startDate:today(),endDate:today(),crew:[],stages:enabledPacks()[0]?.progressStages?.map(name=>({name,pct:0}))||[]};
  openModal(existing?`${p.id} · ${p.name}`:'New project',`<div class="form-grid"><div class="field"><label>Project name</label><input id="pName" value="${esc(p.name)}"></div><div class="field"><label>Client</label><select id="pClient">${state.contacts.map(c=>`<option value="${c.id}" ${c.id===p.clientId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="field full"><label>Site</label><input id="pSite" value="${esc(p.site||'')}"></div><div class="field"><label>Contract excl. GST</label><input type="number" id="pContract" value="${Number(p.contract||0)}"></div><div class="field"><label>Overall progress %</label><input type="number" min="0" max="100" id="pProgress" value="${Number(p.progress||0)}"></div></div><div class="section"><h3>Crew</h3><div class="chip-row">${state.crew.filter(c=>c.role==='worker_crew').map(c=>`<label class="check-chip"><input type="checkbox" class="pCrew" value="${c.id}" ${(p.crew||[]).includes(c.id)?'checked':''}> ${esc(c.name)}</label>`).join('')}</div></div><div class="section"><h3>Progress stages</h3>${(p.stages||[]).map((s,i)=>`<div class="stage-edit"><span>${esc(s.name)}</span><input type="number" min="0" max="100" class="stage-pct" data-index="${i}" value="${Number(s.pct||0)}"></div>`).join('')}</div>`,`<button class="btn" id="saveProject">Save project</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveProject').onclick=()=>{p.name=document.querySelector('#pName').value.trim();p.clientId=document.querySelector('#pClient').value;p.site=document.querySelector('#pSite').value.trim();p.contract=Number(document.querySelector('#pContract').value||0);p.progress=Math.max(0,Math.min(100,Number(document.querySelector('#pProgress').value||0)));p.crew=[...document.querySelectorAll('.pCrew:checked')].map(x=>x.value);document.querySelectorAll('.stage-pct').forEach(x=>p.stages[Number(x.dataset.index)].pct=Math.max(0,Math.min(100,Number(x.value||0))));if(!existing)state.projects.unshift(p);saveState(state);closeModal();render();notify('Project saved')};
}
function scheduleEditor(){openModal('Schedule crew',`<div class="form-grid"><div class="field"><label>Job</label><select id="sProject">${state.projects.filter(p=>p.status==='In progress').map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Date</label><input type="date" id="sDate" value="${today()}"></div><div class="field"><label>Start</label><input type="time" id="sStart" value="07:30"></div><div class="field"><label>Finish</label><input type="time" id="sEnd" value="16:30"></div><div class="field full"><label>Plan / notes</label><input id="sNote"></div></div><div class="section"><h3>Crew</h3>${state.crew.filter(c=>c.role==='worker_crew').map(c=>`<label class="check-chip"><input type="checkbox" class="sCrew" value="${c.id}"> ${esc(c.name)}</label>`).join('')}</div>`,`<button class="btn" id="saveSchedule">Add to schedule</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveSchedule').onclick=()=>{state.schedule.push({id:uid('S'),projectId:document.querySelector('#sProject').value,date:document.querySelector('#sDate').value,start:document.querySelector('#sStart').value,end:document.querySelector('#sEnd').value,crewIds:[...document.querySelectorAll('.sCrew:checked')].map(x=>x.value),note:document.querySelector('#sNote').value.trim()});saveState(state);closeModal();render();notify('Crew scheduled')}}
function clockIn(){const fs=state.fieldSession;fs.clockedIn=true;fs.clockInAt=new Date().toISOString();fs.hnsSigned=false;persist('Clocked in')}
function fieldHns(){const fs=state.fieldSession,p=getProject(fs.projectId),hazards=enabledPacks().flatMap(x=>x.hazards||[]).slice(0,5);state.hnsDocs.push({id:uid('HS'),projectId:p.id,type:'Daily pre-start',date:today(),status:'Signed',crewIds:[fs.crewId],hazards});fs.hnsSigned=true;persist('H&S sign-on completed')}
function fieldProgress(){const p=getProject(state.fieldSession.projectId);openModal('Update progress',`<div class="field"><label>Overall project progress %</label><input type="number" min="0" max="100" id="fpPct" value="${p.progress}"></div><div class="field section"><label>Site note</label><textarea id="fpNote" placeholder="What was completed today?"></textarea></div>`,`<button class="btn" id="saveProgress">Save progress</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveProgress').onclick=()=>{p.progress=Math.max(0,Math.min(100,Number(document.querySelector('#fpPct').value||p.progress)));state.progressUpdates.push({id:uid('PR'),projectId:p.id,date:today(),crewId:state.fieldSession.crewId,percent:p.progress,note:document.querySelector('#fpNote').value.trim(),photos:0});saveState(state);closeModal();render();notify('Progress updated')}}
function fieldPhoto(){const p=getProject(state.fieldSession.projectId);let u=state.progressUpdates.filter(x=>x.projectId===p.id).slice(-1)[0];if(!u){u={id:uid('PR'),projectId:p.id,date:today(),crewId:state.fieldSession.crewId,percent:p.progress,note:'',photos:0};state.progressUpdates.push(u)}u.photos=Number(u.photos||0)+1;persist('Photo evidence recorded')}
function fieldVariation(){const p=getProject(state.fieldSession.projectId);openModal('Flag a variation',`<div class="field"><label>Description</label><textarea id="fvDesc"></textarea></div><div class="field section"><label>Estimated value excl. GST</label><input type="number" id="fvValue" value="0"></div>`,`<button class="btn" id="saveVariation">Send to office</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveVariation').onclick=()=>{state.variations.unshift({id:uid('V'),projectId:p.id,description:document.querySelector('#fvDesc').value.trim(),value:Number(document.querySelector('#fvValue').value||0),status:'Awaiting approval',raisedDate:today(),evidence:'Raised from Field'});state.notifications.unshift({id:uid('N'),type:'variation',message:`Variation raised on ${p.name}`,read:false});saveState(state);closeModal();render();notify('Variation sent to office')}}
function fieldMaterial(){const p=getProject(state.fieldSession.projectId);openModal('Request materials',`<div class="field"><label>Material / item</label><input id="fmItem"></div><div class="field section"><label>Quantity</label><input id="fmQty"></div>`,`<button class="btn" id="saveMaterial">Send request</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveMaterial').onclick=()=>{state.materialRequests.push({id:uid('MR'),projectId:p.id,item:document.querySelector('#fmItem').value.trim(),qty:document.querySelector('#fmQty').value.trim(),status:'Requested',requestedBy:state.fieldSession.crewId,date:today()});saveState(state);closeModal();render();notify('Material request sent')}}
function fieldHazard(fromOffice=false){const projectId=fromOffice?(state.projects[0]?.id||''):state.fieldSession.projectId;openModal('Report hazard / safety issue',`<div class="field"><label>Project</label><select id="fhProject">${state.projects.map(p=>`<option value="${p.id}" ${p.id===projectId?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="field section"><label>Description</label><textarea id="fhDesc"></textarea></div>`,`<button class="btn" id="saveHazard">Create report</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveHazard').onclick=()=>{state.hazardReports.push({id:uid('HZ'),projectId:document.querySelector('#fhProject').value,type:'Hazard',date:today(),description:document.querySelector('#fhDesc').value.trim(),status:'Open'});saveState(state);closeModal();render();notify('Safety report created')}}
function clockOut(){const fs=state.fieldSession;const start=new Date(fs.clockInAt||Date.now());const end=new Date();const hours=Math.max(0,(end-start)/36e5);state.timesheets.unshift({id:uid('TS'),crewId:fs.crewId,projectId:fs.projectId,date:today(),start:start.toTimeString().slice(0,5),end:end.toTimeString().slice(0,5),hours,status:'Pending approval'});fs.clockedIn=false;fs.clockInAt=null;fs.hnsSigned=false;persist('Clocked out and timesheet created')}
function newHnsDoc(){openModal('New H&S document',`<div class="form-grid"><div class="field"><label>Job</label><select id="hsProject">${state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Document type</label><select id="hsType"><option>Daily pre-start</option><option>Site sign-on</option><option>JSA / SWMS</option><option>Toolbox talk</option></select></div></div>`,`<button class="btn" id="saveHns">Create & sign</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveHns').onclick=()=>{state.hnsDocs.push({id:uid('HS'),projectId:document.querySelector('#hsProject').value,type:document.querySelector('#hsType').value,date:today(),status:'Signed',crewIds:[],hazards:enabledPacks().flatMap(x=>x.hazards||[]).slice(0,4)});saveState(state);closeModal();render();notify('H&S document created')}}
function manualTimesheet(){openModal('Add timesheet',`<div class="form-grid"><div class="field"><label>Crew</label><select id="tsCrew">${state.crew.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Job</label><select id="tsProject">${state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Date</label><input type="date" id="tsDate" value="${today()}"></div><div class="field"><label>Hours</label><input type="number" step="0.25" id="tsHours" value="8"></div></div>`,`<button class="btn" id="saveTs">Save timesheet</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveTs').onclick=()=>{state.timesheets.unshift({id:uid('TS'),crewId:document.querySelector('#tsCrew').value,projectId:document.querySelector('#tsProject').value,date:document.querySelector('#tsDate').value,start:'',end:'',hours:Number(document.querySelector('#tsHours').value||0),status:'Pending approval'});saveState(state);closeModal();render();notify('Timesheet saved')}}
function newClaim(){openModal('New progress claim',`<div class="field"><label>Project</label><select id="clProject">${state.projects.filter(p=>p.status==='In progress').map(p=>`<option value="${p.id}">${esc(p.name)} · ${p.progress}%</option>`).join('')}</select></div><div class="notice section">The claim value will be calculated from assessed work value to date less previous claims.</div>`,`<button class="btn" id="saveClaim">Create claim</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveClaim').onclick=()=>{const p=getProject(document.querySelector('#clProject').value),adjusted=adjustedContract(p),valueToDate=projectValueToDate(p),previous=claimedToDate(p.id),value=Math.max(0,valueToDate-previous);state.claims.unshift({id:uid('PC'),projectId:p.id,originalContract:p.contract,approvedVariations:approvedVariations(p.id),adjustedContract:adjusted,progress:p.progress,valueToDate,previousClaims:previous,value,status:'Draft',invoiceId:null,date:today()});saveState(state);closeModal();render();notify('Progress claim created')}}
function newInvoice(claimId=null){const claim=state.claims.find(c=>c.id===claimId);const projectId=claim?.projectId||state.projects[0]?.id||'';const subtotal=claim?.value||0;openModal(claim?`Invoice from ${claim.id}`:'New invoice',`<div class="field"><label>Project</label><select id="iProject">${state.projects.map(p=>`<option value="${p.id}" ${p.id===projectId?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="field section"><label>Subtotal excl. GST</label><input type="number" id="iSubtotal" value="${Number(subtotal)}" ${claim?'readonly':''}></div>`,`<button class="btn" id="saveInvoice">Create invoice</button><button class="btn secondary" id="closeModal2">Cancel</button>`);document.querySelector('#saveInvoice').onclick=()=>{const st=Number(document.querySelector('#iSubtotal').value||0),gst=st*Number(state.settings.taxRate||0.15),inv={id:uid('INV'),projectId:document.querySelector('#iProject').value,claimId:claim?.id||null,subtotal:st,gst,total:st+gst,status:'Draft',date:today()};state.invoices.unshift(inv);if(claim){claim.invoiceId=inv.id;claim.status='Invoiced'}saveState(state);closeModal();render();notify('Tax invoice created')}}

function render(){const views={dashboard,contacts,quotes,tenders,projects,schedule,field,health,rates,timesheets,claims,invoices,reports,settings};shell(views[route]());bind()}

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));}
loadPacks().then(render).catch(err=>{console.error(err);app.innerHTML='<div class="main"><div class="notice">TradeOS failed to load trade packs.</div></div>'});
