import {loadState,saveState,resetState,uid} from './storage.js';

const app=document.querySelector('#app');
let state=loadState();
let route='dashboard';
let packs=[];

const nav=[['dashboard','Dashboard'],['quotes','Quotes'],['projects','Projects'],['schedule','Schedule'],['field','Field'],['health','Health & Safety'],['claims','Claims'],['invoices','Invoices'],['reports','Reports'],['settings','Settings']];
const money=n=>new Intl.NumberFormat('en-NZ',{style:'currency',currency:'NZD',maximumFractionDigits:0}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));

async function loadPacks(){
  const files=['earthworks-landscaping-drainage','painting-decorating','building-carpentry'];
  packs=await Promise.all(files.map(async id=>fetch(`trade-packs/${id}.json`).then(r=>r.json())));
}

function shell(content){
  app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">TradeOS</div><div class="workspace">${esc(state.workspace.name)}<br><span class="muted">NZ contractor operations</span></div><nav class="nav">${nav.map(([id,label])=>`<button data-route="${id}" class="${route===id?'active':''}">${label}</button>`).join('')}</nav></aside><main class="main"><div class="topbar"><div><div class="kicker">${esc(state.workspace.name)}</div><h1>${nav.find(n=>n[0]===route)?.[1]||'TradeOS'}</h1></div><span class="pill">${state.workspace.trades.length} trade pack${state.workspace.trades.length===1?'':'s'} enabled</span></div>${content}</main></div><div class="mobilebar">${nav.map(([id,label])=>`<button data-route="${id}">${label}</button>`).join('')}</div>`;
  document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route=b.dataset.route;render()});
}

function dashboard(){
  const outstanding=state.invoices.filter(i=>i.status!=='Paid').reduce((s,i)=>s+Number(i.total||0),0);
  const unapproved=state.variations.filter(v=>v.status!=='Approved').reduce((s,v)=>s+Number(v.value||0),0);
  return `<section class="hero"><div class="kicker">One operating system for trade contractors</div><h2>Run the office and the site from one place.</h2><p>Quotes, jobs, crew, H&S, field updates, variations, claims and invoices — configured to the trades this company actually performs.</p></section>
  <div class="grid"><div class="card"><div class="label">Active jobs</div><div class="metric">${state.projects.filter(p=>p.status==='In progress').length}</div></div><div class="card"><div class="label">Unapproved variations</div><div class="metric">${money(unapproved)}</div></div><div class="card"><div class="label">Outstanding invoices</div><div class="metric">${money(outstanding)}</div></div><div class="card"><div class="label">Crew</div><div class="metric">${state.crew.length}</div></div></div>
  <section class="section"><h2>Needs attention</h2><div class="card">${state.variations.filter(v=>v.status!=='Approved').length?state.variations.filter(v=>v.status!=='Approved').map(v=>`<div class="row" style="justify-content:space-between;padding:8px 0"><span>${esc(v.project)} · ${esc(v.description)}</span><strong>${money(v.value)}</strong></div>`).join(''):'<div class="empty">No urgent exceptions.</div>'}</div></section>`;
}

function quotes(){return `<div class="row"><button class="btn" id="addQuote">New quote</button></div><section class="section"><div class="card"><table class="table"><thead><tr><th>Quote</th><th>Client</th><th>Scope</th><th>Value</th><th>Status</th></tr></thead><tbody>${state.quotes.map(q=>`<tr><td>${esc(q.id)}</td><td>${esc(q.client)}</td><td>${esc(q.title)}</td><td>${money(q.value)}</td><td>${esc(q.status)}</td></tr>`).join('')}</tbody></table></div></section>`}
function projects(){return `<div class="row"><button class="btn" id="addProject">New project</button></div><section class="section"><div class="card"><table class="table"><thead><tr><th>Job</th><th>Client</th><th>Trade</th><th>Progress</th><th>Contract</th><th>Status</th></tr></thead><tbody>${state.projects.map(p=>`<tr><td>${esc(p.name)}<div class="label">${esc(p.id)}</div></td><td>${esc(p.client)}</td><td>${esc(p.trade)}</td><td>${p.progress}%</td><td>${money(p.contract)}</td><td>${esc(p.status)}</td></tr>`).join('')}</tbody></table></div></section>`}
function schedule(){return `<div class="notice">Scheduling will use enabled trade packs and assigned crew. Google Calendar remains an optional integration; TradeOS stays the source of truth.</div><section class="section"><div class="grid">${state.projects.map(p=>`<div class="card"><div class="kicker">${esc(p.id)}</div><h3>${esc(p.name)}</h3><div class="muted">${esc(p.client)}</div><p>${p.progress}% complete</p></div>`).join('')}</div></section>`}
function field(){const jobs=state.projects.filter(p=>p.status==='In progress');return `<div class="split"><div><div class="card"><div class="kicker">FIELD MODE</div><h2>Today’s jobs</h2>${jobs.map(p=>`<button class="card" style="width:100%;text-align:left;margin-top:10px"><strong>${esc(p.name)}</strong><div class="muted">${esc(p.id)} · ${p.progress}% complete</div></button>`).join('')}</div></div><div class="card"><h3>Field workflow</h3><ol><li>Sign in</li><li>Open assigned job</li><li>Clock in</li><li>Complete site H&S sign-on</li><li>Record progress, photos, materials, hazards and variations</li><li>Clock out</li></ol></div></div>`}
function health(){const enabled=packs.filter(p=>state.workspace.trades.includes(p.id));const hazards=[...new Set(enabled.flatMap(p=>p.hazards||[]))];return `<div class="row"><button class="btn">New H&S document</button></div><section class="section"><div class="split"><div class="card"><h3>Enabled hazard library</h3>${hazards.map(h=>`<div style="padding:7px 0;border-bottom:1px solid #eee">${esc(h)}</div>`).join('')}</div><div class="card"><h3>Company responsibility</h3><p class="muted">Starter H&S content must be reviewed and adopted by the contractor for its actual work, site and legal obligations. TradeOS does not treat templates as automatically compliant.</p></div></div></section>`}
function claims(){return `<div class="notice"><strong>Progress Claim ≠ Tax Invoice.</strong> Claims explain the valuation of work completed. Invoices remain payment/accounting documents.</div><section class="section"><div class="card"><table class="table"><thead><tr><th>Claim</th><th>Project</th><th>Value</th><th>Status</th></tr></thead><tbody>${state.claims.map(c=>`<tr><td>${esc(c.id)}</td><td>${esc(c.project)}</td><td>${money(c.value)}</td><td>${esc(c.status)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No claims yet.</td></tr>'}</tbody></table></div></section>`}
function invoices(){return `<div class="row"><button class="btn" id="addInvoice">New invoice</button></div><section class="section"><div class="card"><table class="table"><thead><tr><th>Invoice</th><th>Project</th><th>Subtotal</th><th>GST</th><th>Total</th><th>Status</th></tr></thead><tbody>${state.invoices.map(i=>`<tr><td>${esc(i.id)}</td><td>${esc(i.project)}</td><td>${money(i.subtotal)}</td><td>${money(i.gst)}</td><td>${money(i.total)}</td><td>${esc(i.status)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No invoices yet.</td></tr>'}</tbody></table></div></section>`}
function reports(){const contract=state.projects.reduce((s,p)=>s+Number(p.contract||0),0);const vars=state.variations.filter(v=>v.status==='Approved').reduce((s,v)=>s+Number(v.value||0),0);return `<div class="grid"><div class="card"><div class="label">Live contract value</div><div class="metric">${money(contract+vars)}</div></div><div class="card"><div class="label">Projects</div><div class="metric">${state.projects.length}</div></div><div class="card"><div class="label">Variations captured</div><div class="metric">${money(state.variations.reduce((s,v)=>s+Number(v.value||0),0))}</div></div><div class="card"><div class="label">Trade packs</div><div class="metric">${state.workspace.trades.length}</div></div></div>`}
function settings(){return `<div class="split"><div class="card"><h3>Company</h3><div class="form-grid"><div class="field"><label>Company name</label><input id="companyName" value="${esc(state.workspace.name)}"></div><div class="field"><label>GST number</label><input id="gst" value="${esc(state.workspace.gst)}"></div><div class="field"><label>Email</label><input id="email" value="${esc(state.workspace.email)}"></div><div class="field"><label>Phone</label><input id="phone" value="${esc(state.workspace.phone)}"></div><div class="field"><label>Bank account</label><input id="bank" value="${esc(state.workspace.bank)}"></div></div><div class="row" style="margin-top:14px"><button class="btn" id="saveCompany">Save company details</button><button class="btn secondary" id="resetDemo">Reset demo</button></div></div><div class="card"><h3>Trade packs</h3>${packs.map(p=>`<label class="trade-card card" style="margin-top:10px"><div class="row"><input type="checkbox" data-pack="${p.id}" ${state.workspace.trades.includes(p.id)?'checked':''}><strong>${esc(p.name)}</strong></div><div class="muted">${esc(p.description)}</div><div class="label">${p.jobTypes.slice(0,4).map(esc).join(' · ')}</div></label>`).join('')}</div></div>`}

function bind(){
  if(route==='quotes') document.querySelector('#addQuote')?.addEventListener('click',()=>{const client=prompt('Client name?');if(!client)return;const title=prompt('Scope / job description?')||'New quote';const value=Number(prompt('Quote value excl. GST?')||0);state.quotes.unshift({id:uid('Q'),client,title,value,status:'Draft'});saveState(state);render()});
  if(route==='projects') document.querySelector('#addProject')?.addEventListener('click',()=>{const name=prompt('Site / project name?');if(!name)return;const client=prompt('Client?')||'';const trade=state.workspace.trades[0]||'';state.projects.unshift({id:uid('PJ'),name,client,trade,progress:0,status:'In progress',contract:0});saveState(state);render()});
  if(route==='invoices') document.querySelector('#addInvoice')?.addEventListener('click',()=>{const project=state.projects[0]?.id||'';const subtotal=Number(prompt('Invoice subtotal excl. GST?')||0);const gst=subtotal*state.settings.taxRate;state.invoices.unshift({id:uid('INV'),project,subtotal,gst,total:subtotal+gst,status:'Draft'});saveState(state);render()});
  if(route==='settings'){
    document.querySelector('#saveCompany')?.addEventListener('click',()=>{for(const [id,key] of [['companyName','name'],['gst','gst'],['email','email'],['phone','phone'],['bank','bank']])state.workspace[key]=document.querySelector('#'+id).value.trim();saveState(state);render()});
    document.querySelector('#resetDemo')?.addEventListener('click',()=>{if(confirm('Reset this local demo?')){state=resetState();render()}});
    document.querySelectorAll('[data-pack]').forEach(cb=>cb.onchange=()=>{const id=cb.dataset.pack;state.workspace.trades=cb.checked?[...new Set([...state.workspace.trades,id])]:state.workspace.trades.filter(x=>x!==id);saveState(state);render()});
  }
}

function render(){const views={dashboard,quotes,projects,schedule,field,health,claims,invoices,reports,settings};shell(views[route]());bind()}

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));}
loadPacks().then(render).catch(err=>{console.error(err);app.innerHTML='<div class="main"><div class="notice">TradeOS failed to load trade packs.</div></div>'});
